name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e51ad129896bc1af79f9417e5509d8d04053eb6a2e2c3f0cd4fff60b68b61d70"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
