name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ad4c6dad5454f05bdfc961ea2874449d0d3648603798615e05bcf3e95191307"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
