name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d20ddd6a89437ff1a93b9b01489ee78110d9be82eaf2388007e8f6db182dc8b"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
