name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85d528cb731a220788a98911caa298ec7b5b87b235cd9bc09f06db76ee777985"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
