name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d125352aa249aebd69ee2f1503696eb4dda34e539cae29bee7e4c0f5129124e9"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
