name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16b74ab173eaab795ea4383ac8b952ded070aa205df2d637a46028347d9a6ba9"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
