name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "387f2729be04e683b2fb6246c0ab38dc8f88bd5365d8d511b029549b15ad7c92"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
