name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5abe204af84e779e3b40ab01ef8d55acfbe1d6cf8b4692006612752e948c5aee"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
