name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9905d36e6d513454eaac34ad1003bc0fdda810c534e71076d63163a3871cf6bc"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
