name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb89db7efaed03a2cb6bbd8c732a5d6a7cf059cfe3621bd20d46bd5a77108275"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
