name = "Soothico"
author = "HypsX"
version = "2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bece2e756974fe3d28933fecd7204e5bb620c828758f3cf055d11293a49a1526"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
