name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "271a5d2413ec559651bfcd82e21c61a2ffa665caeeee3040e77e359aceb7122c"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
