name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86f47f0ee14f40df0df3a32b49e16ae2a61dc5e2c0c6ee182add3747429ec55d"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
