name = "Soothico"
author = "HypsX"
version = "2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c07d2b7ba69458781d8821a3cb0c3cb30dce7a3c3a00d2a8541bbb826d43b4b7"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
