name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "605c9a13b319cd8eafb50501c459ce52b7f32a12f1aedeeeaa096806f1b41674"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
