name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f87ebea04e318a0b3febdd2ee5cb9796eb244c9beb3246dd4055359be1f5fece"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
