name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1db4d074ecc8017eda3691410287daf5dac4bdb7965627a3b8d22ac7cc616a6e"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
