name = "Soothico"
author = "HypsX"
version = "2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e71f226470fd3dfa312ac87bbc3abf72ef6be287178a4b914a240713f7291010"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
